# Generated by Django 5.0.14 on 2025-10-13 09:43

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0054_assistant_knowledgebase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantchatmessage",
            name="action_group_id",
            field=models.UUIDField(
                help_text="Unique identifier for the action group. Can be provided by the client. All the actions done to produce this message can be undone by referencing this ID.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AssistantChatPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "prediction",
                    models.JSONField(
                        default=dict,
                        help_text="The prediction data, including the reasoning and any tool calls.",
                    ),
                ),
                (
                    "human_sentiment",
                    models.SmallIntegerField(
                        choices=[(1, "Like"), (-1, "Dislike")],
                        help_text="Optional feedback provided by the human user on the prediction.",
                        null=True,
                    ),
                ),
                (
                    "human_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Optional feedback provided by the human user on the prediction.",
                    ),
                ),
                (
                    "ai_response",
                    models.OneToOneField(
                        help_text="The AI response message generated as a prediction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="baserow_enterprise.assistantchatmessage",
                    ),
                ),
                (
                    "human_message",
                    models.OneToOneField(
                        help_text="The human message that caused this prediction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="baserow_enterprise.assistantchatmessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
