# Generated by Django 5.0.14 on 2025-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0055_assistantchatmessage_action_group_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebasedocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("raw_document", "Raw Document"),
                    ("baserow_user_docs", "Baserow User Docs"),
                    ("baserow_dev_docs", "Baserow Dev Docs"),
                    ("faq", "FAQ"),
                    ("template", "Template"),
                ],
                default="raw_document",
                max_length=20,
            ),
        ),
    ]
