# Generated by Django 5.0.13 on 2025-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0056_alter_knowledgebasedocument_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="hidden",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Hidden roles are not visible to the user and cannot be "
                          "set. These are used for internal purposes.",
            ),
        ),
    ]
