# Generated by Django 5.0.13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0057_role_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantchat",
            name="message_history",
            field=models.BinaryField(
                blank=True,
                help_text=(
                    "Serialized pydantic-ai message history (JSON bytes) for "
                    "multi-turn conversation context."
                ),
                null=True,
            ),
        ),
    ]
