# Generated by Django 5.2.12 on 2026-03-24 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_enterprise", "0058_assistantchat_message_history"),
        ("core", "0113_alter_notification_options_and_more"),
        ("database", "0206_rowhistory_database_ro_action__6ea699_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataScanResultExportJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "export_charset",
                    models.CharField(
                        choices=[
                            ("utf-8", "utf-8"),
                            ("iso-8859-6", "iso-8859-6"),
                            ("windows-1256", "windows-1256"),
                            ("iso-8859-4", "iso-8859-4"),
                            ("windows-1257", "windows-1257"),
                            ("iso-8859-14", "iso-8859-14"),
                            ("iso-8859-2", "iso-8859-2"),
                            ("windows-1250", "windows-1250"),
                            ("gbk", "gbk"),
                            ("gb18030", "gb18030"),
                            ("big5", "big5"),
                            ("koi8-r", "koi8-r"),
                            ("koi8-u", "koi8-u"),
                            ("iso-8859-5", "iso-8859-5"),
                            ("windows-1251", "windows-1251"),
                            ("x-mac-cyrillic", "mac-cyrillic"),
                            ("iso-8859-7", "iso-8859-7"),
                            ("windows-1253", "windows-1253"),
                            ("iso-8859-8", "iso-8859-8"),
                            ("windows-1255", "windows-1255"),
                            ("euc-jp", "euc-jp"),
                            ("iso-2022-jp", "iso-2022-jp"),
                            ("shift-jis", "shift-jis"),
                            ("euc-kr", "euc-kr"),
                            ("macintosh", "macintosh"),
                            ("iso-8859-10", "iso-8859-10"),
                            ("iso-8859-16", "iso-8859-16"),
                            ("windows-874", "cp874"),
                            ("windows-1254", "windows-1254"),
                            ("windows-1258", "windows-1258"),
                            ("iso-8859-1", "iso-8859-1"),
                            ("windows-1252", "windows-1252"),
                            ("iso-8859-3", "iso-8859-3"),
                        ],
                        default="utf-8",
                        max_length=32,
                    ),
                ),
                (
                    "csv_column_separator",
                    models.CharField(
                        choices=[
                            (",", ","),
                            (";", ";"),
                            ("|", "|"),
                            ("tab", "\t"),
                            ("record_separator", "\x1e"),
                            ("unit_separator", "\x1f"),
                        ],
                        default=",",
                        max_length=32,
                    ),
                ),
                ("csv_first_row_header", models.BooleanField(default=True)),
                ("filter_scan_id", models.PositiveIntegerField(null=True)),
                ("exported_file_name", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job",),
        ),
        migrations.CreateModel(
            name="DataScan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("pattern", "Pattern"),
                            ("list_of_values", "List of values"),
                            ("list_table", "List Table"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pattern", models.TextField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("scan_all_workspaces", models.BooleanField(default=True)),
                ("is_running", models.BooleanField(default=False)),
                ("last_run_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.field",
                    ),
                ),
                (
                    "source_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.table",
                    ),
                ),
                ("workspaces", models.ManyToManyField(blank=True, to="core.workspace")),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="DataScanListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_items",
                        to="baserow_enterprise.datascan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataScanResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.IntegerField()),
                ("matched_value", models.TextField()),
                ("first_identified_on", models.DateTimeField(db_index=True)),
                ("last_identified_on", models.DateTimeField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.field"
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="baserow_enterprise.datascan",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.table"
                    ),
                ),
            ],
            options={
                "ordering": ["-first_identified_on"],
                "indexes": [
                    models.Index(
                        fields=["scan", "first_identified_on"],
                        name="baserow_ent_scan_id_694735_idx",
                    )
                ],
                "unique_together": {("scan", "table", "row_id", "field")},
            },
        ),
    ]
