# Generated by Django 5.0.14 on 2025-10-15 10:50

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0063_element_html_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageelement",
            name="image_url",
            field=baserow.core.formula.field.FormulaField(
                blank=True, default="", help_text="A link to the image file", null=True
            ),
        ),
    ]
