# Generated by Django 5.0.14 on 2025-11-09 10:09

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0065_aiagentworkflowaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="visibility_condition",
            field=baserow.core.formula.field.FormulaField(
                blank=True,
                default="",
                help_text="Change element visibility depending on a formula value",
                null=True,
            ),
        ),
    ]
