[pytest]
DJANGO_SETTINGS_MODULE = baserow.config.settings.test
python_files = test_*.py
markers =
    eval: mark test as an eval test (requires LLM API key)
    data_scanner: mark test as a data scanner test
env =
    DJANGO_SETTINGS_MODULE = baserow.config.settings.test
