# Generated by Django 5.2.11 on 2026-03-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_squashed_0023_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationworkflowhistory',
            name='event_payload',
            field=models.JSONField(blank=True, db_default=None, help_text='Event payload received by the workflow.', null=True),
        ),
        migrations.AddField(
            model_name='automationworkflowhistory',
            name='simulate_until_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_histories', to='automation.automationnode'),
        ),
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='is_test_run',
            field=models.BooleanField(db_default=False, help_text='True when the workflow is being simulated.'),
        ),
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_histories', to='automation.automationworkflow'),
        ),
        migrations.CreateModel(
            name='AutomationNodeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_test_run', models.BooleanField(db_default=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('disabled', 'Disabled'), ('started', 'Started')], max_length=8)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_histories', to='automation.automationnode')),
                ('workflow_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_histories', to='automation.automationworkflowhistory')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationNodeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.PositiveIntegerField(db_default=0, help_text='Keeps track of the current iteration of the Iterator node.')),
                ('result', models.JSONField(db_default={}, help_text='Contains node results.')),
                ('node_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_results', to='automation.automationnodehistory')),
            ],
        ),
        migrations.AddIndex(
            model_name='automationnodehistory',
            index=models.Index(fields=['workflow_history', 'node'], name='automation__workflo_fa3be6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationnoderesult',
            unique_together={('node_history', 'iteration')},
        ),
    ]
