# Generated by Django 5.2.12 on 2026-03-19 10:23

from django.db import migrations, models
from django.db.models import CharField
from django.db.models.functions import Cast


def populate_iteration_path(apps, schema_editor):
    AutomationNodeResult = apps.get_model("automation", "AutomationNodeResult")
    AutomationNodeResult.objects.update(
        iteration_path=Cast("iteration", output_field=CharField())
    )


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_automationworkflowhistory_event_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationnoderesult',
            name='iteration_path',
            field=models.CharField(db_default='', default='', help_text='Keeps track of the iteration path that generated the result.'),
        ),
        migrations.RunPython(populate_iteration_path, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='automationnodehistory',
            name='is_test_run',
        ),
    ]
