# Generated by Django 5.2.12 on 2026-03-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_automationnoderesult_iteration_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationworkflow',
            unique_together=set(),
        ),
    ]
