# Generated by Django 5.2.13 on 2026-04-13 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_alter_automationworkflow_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationnodehistory',
            options={'ordering': ('-started_on', 'id')},
        ),
        migrations.AlterModelOptions(
            name='automationworkflowhistory',
            options={'ordering': ('-started_on', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='automationnoderesult',
            unique_together={('node_history', 'iteration_path')},
        ),
        migrations.AddIndex(
            model_name='automationworkflowhistory',
            index=models.Index(fields=['workflow', '-started_on'], name='wa_hist_started_idx'),
        ),
        migrations.AddIndex(
            model_name='automationworkflowhistory',
            index=models.Index(fields=['workflow', 'status', '-started_on'], name='wa_hist_status_started_idx'),
        ),
        migrations.RemoveField(
            model_name='automationnoderesult',
            name='iteration',
        ),
        migrations.AddField(
            model_name='automationworkflow',
            name='notification_recipients',
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    'The workspace users that should receive notifications related '
                    'to this workflow.'
                ),
                related_name='automation_notification_workflows',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
