# Generated by Django 5.0.14 on 2025-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0201_increase_pendingsearchvalueupdate_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="missing_m2m_indexes_added",
            field=models.BooleanField(
                db_default=False,
                default=True,
                help_text="Indicates whether potentially missing m2m foreign key indexes have been added.",
            ),
        ),
    ]
