# Generated by Django 5.2.10 on 2026-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0202_table_missing_m2m_indexes_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_dependencies',
            field=models.ManyToManyField(related_name='dependant_fields', through='database.FieldDependency', through_fields=('dependant', 'dependency'), to='database.field'),
        ),
    ]
