# Generated by Django 5.2.12 on 2026-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('database', '0205_formvieweditrowfield'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "database_ro_action__6ea699_idx" ON "database_rowhistory" ("action_timestamp")',
            reverse_sql='DROP INDEX IF EXISTS "database_ro_action__6ea699_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name='rowhistory',
                    index=models.Index(fields=['action_timestamp'], name='database_ro_action__6ea699_idx'),
                ),
            ],
        ),
    ]
