# Generated by Django 5.2.12 on 2026-03-17 09:16

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('database', '0205_formvieweditrowfield'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='rowhistory',
            index=models.Index(fields=['action_timestamp'], name='database_ro_action__6ea699_idx'),
        ),
    ]
