# Generated by Django 5.2.12 on 2026-03-31 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0206_rowhistory_database_ro_action__6ea699_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDefaultValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this default value is active.')),
                ('value', models.JSONField(default=None, help_text='The raw default value in API request format.', null=True)),
                ('field_type', models.CharField(help_text='The field type identifier at the time the value was stored. Used to detect incompatibility when the field type changes.', max_length=64, null=True)),
                ('function', models.CharField(help_text="Optional function name (e.g. 'now') to resolve the default value dynamically at row creation time instead of using the stored value.", max_length=64, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.field')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_default_values', to='database.view')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [
                    models.UniqueConstraint(
                        fields=['view', 'field'],
                        name='unique_view_field_default_value',
                    )
                ],
            },
        ),
    ]
