events {

}

error_log /dev/stdout info;

http {
    access_log /dev/stdout;
    client_max_body_size 20m;

    map $arg_dl $baserow_media_content_disposition {
        default "attachment; filename=$arg_dl";
        "" "";
    }

    server {
        server_name example.localhost;

        location ~ ^/(api|ws)/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://backend:8000;
        }

        location /media/ {
            add_header Content-Disposition $baserow_media_content_disposition always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header Content-Security-Policy "sandbox; default-src 'none'; script-src 'none'; object-src 'none'; base-uri 'none'" always;
            # TODO Change to your media folder location!
            alias /baserow/media/;
        }

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_pass http://web-frontend:3000;
        }
    }
}
