# Generated by Django 5.0.14 on 2025-11-12 21:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0029_ai_field_auto_update"),
        ("core", "0107_twofactorauthprovidermodel_totpauthprovidermodel_and_more"),
        ("database", "0200_fix_to_timestamptz_formula"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerateAIValuesJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "user_ip_address",
                    models.GenericIPAddressField(
                        help_text="The user IP address.", null=True
                    ),
                ),
                (
                    "user_websocket_id",
                    models.CharField(
                        help_text="The user websocket uuid needed to manage signals sent correctly.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_session_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "user_action_group_id",
                    models.CharField(
                        help_text="The user session uuid needed for undo/redo action group functionality.",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "row_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        help_text="If provided, the row IDs to generate AI values for.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "view_id",
                    models.IntegerField(
                        help_text="If provided, the view ID to generate AI values for.",
                        null=True,
                    ),
                ),
                (
                    "only_empty",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to only generate values for empty cells.",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        help_text="The AI field to generate values for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job", models.Model),
        ),
    ]
