# Generated by Django 5.0.14 on 2025-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baserow_premium", "0030_generateaivaluesjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateaivaluesjob",
            name="is_auto_update",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="If set, the job has been scheduled as a result of AI field auto-update.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AIFieldScheduledUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_id",
                    models.IntegerField(help_text="The ID of the field to update."),
                ),
                ("row_id", models.IntegerField(help_text="Row ID to update")),
                (
                    "updated_on",
                    models.DateTimeField(
                        help_text="The time this update was last modified."
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["field_id", "-updated_on"],
                        name="ai_field_updated_on_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="aifieldscheduledupdate",
            constraint=models.UniqueConstraint(
                fields=("field_id", "row_id"), name="ai_field_id_row_id_uniq"
            ),
        ),
    ]
