# Generated by Django 5.0.14 on 2025-10-15 10:50

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0020_corehttptriggerservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localbaserowaggregaterows",
            name="search_query",
            field=baserow.core.formula.field.FormulaField(
                blank=True,
                default="",
                help_text="The query to apply to the service to narrow the results down.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localbaserowgetrow",
            name="search_query",
            field=baserow.core.formula.field.FormulaField(
                blank=True,
                default="",
                help_text="The query to apply to the service to narrow the results down.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localbaserowlistrows",
            name="search_query",
            field=baserow.core.formula.field.FormulaField(
                blank=True,
                default="",
                help_text="The query to apply to the service to narrow the results down.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="localbaserowupsertrow",
            name="row_id",
            field=baserow.core.formula.field.FormulaField(
                blank=True, default="", null=True
            ),
        ),
    ]
