# Generated by Django 5.0.14 on 2026-01-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0024_slack_integration_write_message_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreperiodicservice",
            name="next_run_at",
            field=models.DateTimeField(
                db_index=True,
                help_text="The next scheduled time for this service to run. "
                "Automatically calculated based on the interval and schedule fields.",
                null=True,
                db_default=None,
            ),
        ),
    ]
