# Generated by Django 5.0.14 on 2025-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_twofactorauthprovidermodel_totpauthprovidermodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="unique",
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
