# Generated by Django 5.2.11 on 2026-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_alter_twofactorauthprovidermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.TextField(choices=[('en', 'English'), ('fr', 'French'), ('nl', 'Dutch'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian'), ('pl', 'Polish'), ('ko', 'Korean'), ('uk', 'Ukrainian')], default='en', help_text='An ISO 639 language code (with optional variant) selected by the user. Ex: en-GB.', max_length=10),
        ),
    ]
