# Generated by Django 5.2.11 on 2026-02-23 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0112_alter_userprofile_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_on', '-id']},
        ),
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'ordering': ['-created_on', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_created_8ed1ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrecipient',
            name='core_notifi_created_06e5e6_idx',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "core_notifi_created_7f4b88_idx" ON "core_notification" ("created_on" DESC, "id" DESC)',
            reverse_sql='DROP INDEX IF EXISTS "core_notifi_created_7f4b88_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name='notification',
                    index=models.Index(fields=['-created_on', '-id'], name='core_notifi_created_7f4b88_idx'),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "core_notifi_created_4b2233_idx" ON "core_notificationrecipient" ("created_on" DESC, "id" DESC)',
            reverse_sql='DROP INDEX IF EXISTS "core_notifi_created_4b2233_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name='notificationrecipient',
                    index=models.Index(fields=['-created_on', '-id'], name='core_notifi_created_4b2233_idx'),
                ),
            ],
        ),
    ]
