# Generated by Django 5.2.13 on 2026-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='message',
            field=models.TextField(default='', help_text='Deprecated legacy field retained for compatibility. This message is not exposed to invitation recipients.', max_length=250),
        ),
    ]
